# docker-compose.yml
version: '3'
networks:
  todoapp-net:
services:
  pythonapp:
    image: todoapp:2.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=app_db
      - DB_USER=app_user
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=3306
    networks:
      - todoapp-net
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mysql-local:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - todoapp-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    networks:
      - todoapp-net
volumes:
  todoapp-db-data:
